version: "3.9"

name: data-challenge-latch

x-common-env-vars:
  &common-env-vars
  env_file:
    - ./.env

services:
  postgres:
    <<: *common-env-vars
    container_name: postgres
    hostname: postgres
    image: postgres:${POSTGRES_VERSION:-14.7}
    ports:
      - ${POSTGRES_EXT_PORT:-5440}:${POSTGRES_PORT:-5432}
    restart: unless-stopped
    volumes:
      - ./scripts/postgres_init.sh:/docker-entrypoint-initdb.d/postgres_init.sh:rwx
      - ./data-challenge_sfrpt/crimes.sql:/docker-entrypoint-initdb.d/crimes.sql
    healthcheck:
      test: 
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  load-data:
    <<: *common-env-vars
    container_name: load-data
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /code
    command: poetry run python3 -q data-challenge_sfrpt/loader.py
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
